{% set name = "Hypercorn" %}
{% set version = "0.14.3" %}
{% set sha256 = "4a87a0b7bbe9dc75fab06dbe4b301b9b90416e9866c23a377df21a969d6ab8dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - hypercorn = hypercorn.__main__:main
  skip: true  # [py < 37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - poetry-core >=1.0.0
  run:
    - python
    - h11 >=0.8.1
    - h2 >=3.1.0
    - priority
    - toml >=0.10.0
    - typing_extensions >=3.7.4
    - wsproto >=0.14.0
    - uvloop >=0.11.3  # [unix]
    - trio >=0.11.0

test:
  imports:
    - hypercorn
  commands:
    - hypercorn --help

about:
  home: https://gitlab.com/pgjones/hypercorn/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A ASGI Server based on Hyper libraries and inspired by Gunicorn.
  description: |
    Hypercorn is an ASGI web server based on the sans-io hyper, h11, h2,
    and wsproto libraries and inspired by Gunicorn. Hypercorn supports HTTP/1, HTTP/2,
    and websockets and the ASGI 2 specification. Hypercorn can utilise asyncio,
    uvloop, or trio worker types.
  doc_url: https://pgjones.gitlab.io/hypercorn/
  dev_url: https://gitlab.com/pgjones/hypercorn/

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
    - synapticarbors
